name: Publish

on:
  push:
    branches:
      - core22

jobs:
  publish_amd64:
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
    steps:
    - uses: actions/checkout@v3
    - uses: snapcore/action-build@v1
      id: build
    - uses: snapcore/action-publish@v1
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: candidate
